# Generated by Django 6.0.5 on 2026-05-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditlogLogentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.CharField(max_length=255)),
                ('object_id', models.BigIntegerField(blank=True, null=True)),
                ('object_repr', models.TextField()),
                ('action', models.SmallIntegerField()),
                ('changes', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('serialized_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auditlog_logentry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappCykl',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('publiczne', models.BooleanField()),
                ('edytowalne', models.BooleanField()),
                ('opis', models.TextField()),
                ('desc', models.TextField()),
                ('abstrakcyjny', models.BooleanField()),
                ('szablon_karty', models.CharField(max_length=128)),
                ('prk', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Swierkapp_cykl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappCyklAdministratorzy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Swierkapp_cykl_administratorzy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappDyscyplina',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Swierkapp_dyscyplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappDziedzina',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Swierkapp_dziedzina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappEfektkierunkowy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=32)),
                ('opis', models.TextField()),
                ('desc', models.TextField()),
                ('rodzaj', models.CharField(max_length=2)),
                ('edytowalne', models.BooleanField()),
            ],
            options={
                'db_table': 'Swierkapp_efektkierunkowy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappEfektkierunkowyEfektyObszarowe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Swierkapp_efektkierunkowy_efekty_obszarowe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappEfektobszarowy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=16)),
                ('opis', models.TextField()),
                ('desc', models.TextField()),
                ('rodzaj', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'Swierkapp_efektobszarowy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappEfektprzedmiotowy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=32)),
                ('opis', models.TextField()),
                ('desc', models.TextField()),
                ('metoda_weryfikacji', models.TextField()),
                ('verification_method', models.TextField()),
                ('forma_metody_weryfikacji', models.TextField()),
                ('class_form', models.TextField()),
                ('publiczne', models.BooleanField()),
                ('edytowalne', models.BooleanField()),
                ('rodzaj', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'Swierkapp_efektprzedmiotowy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappEfektprzedmiotowyEfektyKierunkowe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Swierkapp_efektprzedmiotowy_efekty_kierunkowe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappGrupaefektowkierunkowych',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_od', models.DateField()),
                ('opis', models.TextField()),
                ('desc', models.TextField()),
                ('publiczne', models.BooleanField()),
                ('edytowalne', models.BooleanField()),
            ],
            options={
                'db_table': 'Swierkapp_grupaefektowkierunkowych',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappGrupaefektowkierunkowychAdministratorzy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Swierkapp_grupaefektowkierunkowych_administratorzy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappGrupaefektowkierunkowychInneDyscypliny',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Swierkapp_grupaefektowkierunkowych_inne_dyscypliny',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappGrupaefektowobszarowych',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_od', models.DateField()),
                ('opis', models.TextField()),
                ('desc', models.TextField()),
            ],
            options={
                'db_table': 'Swierkapp_grupaefektowobszarowych',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappGrupaefektowobszarowychAdministratorzy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Swierkapp_grupaefektowobszarowych_administratorzy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappJednostka',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Swierkapp_jednostka',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappKarta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zalozenia', models.TextField()),
                ('goals', models.TextField()),
                ('zaliczenie', models.TextField()),
                ('evaluation_form', models.TextField()),
                ('tresci', models.TextField()),
                ('content', models.TextField()),
                ('godziny_kontaktowe', models.CharField(max_length=64)),
                ('godziny_kontaktowe_ects', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('godziny_praktyczne', models.CharField(max_length=64)),
                ('godziny_praktyczne_ects', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('literatura_podstawowa', models.TextField()),
                ('literatura_uzupelniajaca', models.TextField()),
                ('essential_literature', models.TextField()),
                ('further_reading', models.TextField()),
                ('data', models.DateField()),
                ('publiczne', models.BooleanField()),
                ('edytowalne', models.BooleanField()),
                ('assessment_conditions', models.TextField(blank=True, null=True)),
                ('metody_dydaktyczne_stacjonarne', models.TextField(blank=True, null=True)),
                ('metody_dydaktyczne_zdalne', models.TextField(blank=True, null=True)),
                ('skopiuj_efekty_z_eu', models.BooleanField(db_column='skopiuj_efekty_z_EU')),
                ('teaching_methods_in_person', models.TextField(blank=True, null=True)),
                ('teaching_methods_online', models.TextField(blank=True, null=True)),
                ('warunki_zaliczenia', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Swierkapp_karta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappKartaMetody',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Swierkapp_karta_metody',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappKartaMetodyZdalne',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Swierkapp_karta_metody_zdalne',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappKartaProwadzacy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Swierkapp_karta_prowadzacy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappKartaPrzedmiotyWprowadzajace',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Swierkapp_karta_przedmioty_wprowadzajace',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappKartaZakladaneEfektyKierunkoweKompetencje',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Swierkapp_karta_zakladane_efekty_kierunkowe_kompetencje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappKartaZakladaneEfektyKierunkoweUmiejetnosci',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Swierkapp_karta_zakladane_efekty_kierunkowe_umiejetnosci',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappKartaZakladaneEfektyKierunkoweWiedza',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Swierkapp_karta_zakladane_efekty_kierunkowe_wiedza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappKategoriaprzedmiotu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'Swierkapp_kategoriaprzedmiotu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappKierunek',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Swierkapp_kierunek',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappMetodadydaktyczna',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nazwa', models.TextField()),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'Swierkapp_metodadydaktyczna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappNazwaprzedmiotu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'Swierkapp_nazwaprzedmiotu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappPraca',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nr', models.SmallIntegerField()),
                ('praktyczne', models.BooleanField()),
                ('kontaktowe', models.BooleanField()),
                ('opis', models.TextField()),
                ('desc', models.TextField()),
                ('wyliczenie', models.CharField(blank=True, max_length=32, null=True)),
                ('liczba_godzin', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'Swierkapp_praca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappPrzedmiot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kod', models.CharField(max_length=16)),
                ('rodzaj', models.CharField(max_length=16)),
                ('sztuczny', models.BooleanField()),
                ('egzamin', models.BooleanField()),
                ('sem', models.SmallIntegerField()),
                ('ects', models.SmallIntegerField()),
                ('liczba_godzin_w', models.SmallIntegerField(db_column='liczba_godzin_W')),
                ('liczba_godzin_c', models.SmallIntegerField(db_column='liczba_godzin_C')),
                ('liczba_godzin_ps', models.SmallIntegerField(db_column='liczba_godzin_PS')),
                ('liczba_godzin_l', models.SmallIntegerField(db_column='liczba_godzin_L')),
                ('liczba_godzin_p', models.SmallIntegerField(db_column='liczba_godzin_P')),
                ('liczba_godzin_s', models.SmallIntegerField(db_column='liczba_godzin_S')),
                ('publiczne', models.BooleanField()),
                ('framework_content', models.TextField()),
                ('goals', models.TextField()),
                ('info_dzialalnosc_naukowa', models.BooleanField()),
                ('info_umiejetnosci_praktyczne', models.BooleanField()),
                ('info_zrownowazony_rozwoj', models.BooleanField()),
                ('tresci_ramowe', models.TextField()),
                ('zalozenia', models.TextField()),
                ('edytowalne', models.BooleanField()),
                ('data', models.DateField()),
            ],
            options={
                'db_table': 'Swierkapp_przedmiot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappPrzedmiotEfektyKierunkowe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Swierkapp_przedmiot_efekty_kierunkowe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappPrzedmiotKoordynatorzy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Swierkapp_przedmiot_koordynatorzy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappPrzedmiotOpiekunowie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Swierkapp_przedmiot_opiekunowie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappPrzedmiotPulaPrzedmiotow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Swierkapp_przedmiot_pula_przedmiotow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappSemestr',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rok_akademicki', models.IntegerField()),
                ('zimowy_letni', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'Swierkapp_semestr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappSpecjalnosc',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'Swierkapp_specjalnosc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappStudia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('liczba_semestrow', models.SmallIntegerField()),
                ('opis', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=64)),
                ('stopien', models.CharField(max_length=8)),
                ('forma', models.CharField(blank=True, max_length=16, null=True)),
                ('profil', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'Swierkapp_studia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('is_teacher', models.BooleanField()),
                ('is_administrator_siatek', models.BooleanField()),
                ('tytul', models.CharField(blank=True, max_length=64, null=True)),
                ('stanowisko', models.CharField(blank=True, max_length=64, null=True)),
                ('firma', models.CharField(blank=True, max_length=128, null=True)),
                ('token', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'Swierkapp_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Swierkapp_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwierkappUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Swierkapp_user_user_permissions',
                'managed': False,
            },
        ),
    ]
