version: "3.9"

services:
  db:
    image: postgres:16
    container_name: sylabus_db

    restart: unless-stopped

    environment:
      POSTGRES_DB: sylabus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/full_backup.sql:/docker-entrypoint-initdb.d/full_backup.sql

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .

    container_name: sylabus_web

    restart: unless-stopped

    command: >
      sh -c "
      python manage.py runserver 0.0.0.0:8000
      "

    volumes:
      - .:/app

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy

    env_file:
      - .env

volumes:
  postgres_data:
